### ISSUE TITLE
Support for python3?

### ISSUE THREAD

**Issue by pphase** [pangduckwai/PiDisplay#5]
Hi,
I see that your script has not been updated since quite some time. As I have issues with python 2 (cannot install luma.core) I wonder if you thought about making script work with python3? My python knowledge is very poor and keep getting errors when I try to launch it with python3:
```

$ sudo python3 monitor.py
  File "monitor.py", line 144
    print ''.join(pwdLst) 
           ^
SyntaxError: invalid syntax
```

after changing it to proper values I get one more place to work with:

```
$ sudo python3 monitor.py
  File "monitor.py", line 427
    print "Stopped", sys.exc_info()[0]
                          ^
SyntaxError: invalid syntax
```

Then I get:

```
$ sudo python3 monitor.py
/usr/local/lib/python3.7/dist-packages/luma/core/interface/serial.py:200: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  self._gpio.setup(pin, self._gpio.OUT)
Traceback (most recent call last):
  File "monitor.py", line 416, in <module>
    iface = subprocess.check_output("iwgetid | awk '{print $1}'", shell = True).rstrip("\r\n")
TypeError: a bytes-like object is required, not 'str'
```
And at this point it is beyond my knowledge.

Is there any chance you might help me?

I am usign script on RaspberryPi Zero W v1.1 with Raspian 10 (5.10.60+)

Thanks in advance for your help!

**Comment by pangduckwai** [comment]
Hello, sorry for the late reply. Sadly I am not very good at Python either,
and I was not following the activities in this repository closely enough.

In fact I'm aware of the outdated Python issue, as someone else pointed it
out to me (see the closed issues). I wanted to have it updated but was
unable to find the time yet... In the mean time maybe you can take a look
at the closed issues in the repo to see if those help?

**Comment by spartan195** [comment]
Greeting, project has been updated to work with python3, Tested on a raspberry pi W with raspbian stretch. Check the readme for the specific version if it doesn't work on your current one :+1:
